# Generated by Django 2.2 on 2022-02-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_moderated',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
