# Generated by Django 2.2 on 2022-02-08 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_auto_20220207_2315'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
