# Generated by Django 2.2 on 2022-02-10 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_moderated',
            new_name='is_verified',
        ),
    ]
