# Generated by Django 2.2 on 2022-02-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0010_auto_20220216_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='news_count',
            field=models.IntegerField(default=0),
        ),
    ]
