# Generated by Django 2.2 on 2022-03-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0013_auto_20220310_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, default='profile_images/defaultuser.png', null=True, upload_to='profile_images/<function user_directory_path at 0x000002630A330F70>/', verbose_name='image'),
        ),
    ]
