# Generated by Django 2.2 on 2022-03-10 15:35

import app_users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0014_auto_20220310_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, default='profile_images/defaultuser.png', null=True, upload_to=app_users.models.user_directory_path, verbose_name='image'),
        ),
    ]
