# Generated by Django 2.2 on 2022-03-28 15:58

import app_users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0018_auto_20220325_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_head_img',
            field=models.ImageField(blank=True, default='profile_images/defaulthead.png', null=True, upload_to=app_users.models.user_directory_path, verbose_name='head image'),
        ),
    ]
