# Generated by Django 2.2 on 2022-02-17 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_auto_20220216_0254'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
