# Generated by Django 2.2 on 2022-03-25 19:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news_board', '0006_auto_20220325_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='likes'),
        ),
        migrations.AlterField(
            model_name='news',
            name='saves',
            field=models.ManyToManyField(related_name='saves', to=settings.AUTH_USER_MODEL, verbose_name='saves'),
        ),
    ]
