# Generated by Django 2.2 on 2022-03-25 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news_board', '0008_auto_20220325_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=1500, null=True, verbose_name='title'),
        ),
    ]
