# Generated by Django 3.2.6 on 2022-04-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news_board', '0010_auto_20220329_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_at'),
        ),
    ]
