# Generated by Django 3.2.6 on 2022-04-05 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news_board', '0011_comment_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
