# Generated by Django 3.2.6 on 2022-04-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news_board', '0012_remove_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is_active'),
        ),
    ]
