# Generated by Django 3.2.6 on 2022-04-13 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news_board', '0013_alter_news_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-id'], 'verbose_name': 'new', 'verbose_name_plural': 'news'},
        ),
    ]
